name: wap-integration-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  duckdb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration_tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package
        working-directory: .
        run: pip install -e ".[dev]"

      - name: Install addons
        run: dbt-addons install

      - name: Seed
        run: dbt seed --profiles-dir .
        

      - name: Build & publish
        run: dbt-addons build --wap --profiles-dir .
